Traceback (most recent call last):
  File "/Users/paulmackay/Desktop/Python/Debugging/boxExample.py", line 34, in <module>
    raise Exception('This is the error message.')
Exception: This is the error message.
Traceback (most recent call last):
  File "/Users/paulmackay/Desktop/Python/Debugging/boxExample.py", line 34, in <module>
    raise Exception('This is the error message.')
Exception: This is the error message.
